"""empty message

Revision ID: 836892799698
Revises: ee99a5882d3d
Create Date: 2020-09-21 10:00:57.970616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836892799698'
down_revision = 'ee99a5882d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('registered_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'registered_on')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
